   alarm: amdgpu_dgpu_edge_temp
      on: sensors.temperature_amdgpu-pci-0300_temp1_edge_input
   class: Utilization
    type: System
component: Hardware
  lookup: max -1m unaligned of input
   units: Celsius
   every: 30s
    warn: $this > 80
    crit: $this > 85
   delay: down 5m multiplier 1.5 max 1h
      to: alerts
    info: AMD dGPU (RX 9060 XT) edge temperature
